project:
  type: website

format:
  html:
    theme: journal
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    left:
      - text: "Blog"
        href: blog/index.qmd
    background: dark
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]