# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spot-check',
                'doc_host': 'https://januff.github.io',
                'git_url': 'https://github.com/januff/spot-check',
                'lib_path': 'spot_check'},
  'syms': {'spot_check.core': {'spot_check.core.foo': ('core.html#foo', 'spot_check/core.py')}}}
